name: eurelinks_beta
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  # cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  path_provider: ^2.0.11
  date_field: ^3.0.2
  image_picker: ^0.8.6+1
  permission_handler: ^10.2.0
  syncfusion_flutter_calendar: ^20.4.44
  path: ^1.8.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.16
  table_calendar: ^3.0.8
  firebase_storage: ^11.0.10
  url_launcher: ^5.0.2
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
