// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'firebase_options.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASKa2r20c3osyfWOECWn2jYXxR_jAXZu0',
    appId: '1:1022748842502:web:42cc05d40d41c7ab384187',
    messagingSenderId: '1022748842502',
    projectId: 'eurelink',
    authDomain: 'eurelink.firebaseapp.com',
    storageBucket: 'eurelink.appspot.com',
    measurementId: 'G-5Y5985CXVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2RvXnN6vnOk_LVfklSh6HSwV878U-kUY',
    appId: '1:1022748842502:android:7bed2fb519a99cd8384187',
    messagingSenderId: '1022748842502',
    projectId: 'eurelink',
    storageBucket: 'eurelink.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRveu-qstjyzibpKNfJ_7Jn6Gf4oH1OPI',
    appId: '1:1022748842502:ios:10445d99727782eb384187',
    messagingSenderId: '1022748842502',
    projectId: 'eurelink',
    storageBucket: 'eurelink.appspot.com',
    iosClientId:
        '1022748842502-bgq9eujgagekuvcm6lund22q79njfs4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.eurelinksBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRveu-qstjyzibpKNfJ_7Jn6Gf4oH1OPI',
    appId: '1:1022748842502:ios:10445d99727782eb384187',
    messagingSenderId: '1022748842502',
    projectId: 'eurelink',
    storageBucket: 'eurelink.appspot.com',
    iosClientId:
        '1022748842502-bgq9eujgagekuvcm6lund22q79njfs4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.eurelinksBeta',
  );
}
